"""
post_review.py — Standalone script run by GitHub Actions.

Reads the PR URL from the environment, runs the full review pipeline,
formats results as Markdown, and posts them as a PR comment.

Run locally:  PR_URL=https://github.com/owner/repo/pull/1 uv run python backend/scripts/post_review.py
Run in CI:    Set PR_URL, GITHUB_TOKEN, and GROQ_API_KEY as environment variables / secrets.
"""

import asyncio
import os
import sys
from github import Github


def format_suggestion_md(suggestion) -> str:
    """Formats one Suggestion as a Markdown block for the PR comment."""
    # Emoji per type — makes the comment scannable at a glance
    icons = {
        "bug": "🐛",
        "security": "🔒",
        "test": "🧪",
        "review": "💡",
    }
    icon = icons.get(suggestion.suggestion_type, "💡")
    confidence_pct = int(suggestion.confidence * 100)
    confidence_bar = "█" * (confidence_pct // 10) + "░" * (10 - confidence_pct // 10)

    lines = [
        f"### {icon} `{suggestion.suggestion_type.upper()}` — `{suggestion.file_path}:{suggestion.line_start}`",
        f"> Confidence: {confidence_bar} {confidence_pct}%",
        "",
        suggestion.message,
    ]

    if suggestion.suggested_fix:
        lines += [
            "",
            "<details>",
            "<summary>💻 Suggested fix</summary>",
            "",
            "```python",
            suggestion.suggested_fix,
            "```",
            "",
            "</details>",
        ]

    return "\n".join(lines)


def format_comment(pr_url: str, result) -> str:
    """Builds the full PR comment body from a ReviewResponse."""
    header = (
        "## 🤖 AI Code Review\n\n"
        f"**{result.total_suggestions} suggestion{'s' if result.total_suggestions != 1 else ''}** "
        f"found in `{result.repo}` PR #{result.pr_number} "
        f"_(processed in {result.processing_time_seconds}s using LLaMA-3)_\n\n"
    )

    if result.total_suggestions == 0:
        return header + "✅ No issues found. Looks good!\n"

    # Group by type for a structured layout
    by_type = {}
    for s in result.suggestions:
        by_type.setdefault(s.suggestion_type, []).append(s)

    sections = []
    # Show in priority order: security first, then bugs, then review, then tests
    for stype in ["security", "bug", "review", "test"]:
        if stype in by_type:
            for s in by_type[stype]:
                sections.append(format_suggestion_md(s))
                sections.append("---")

    footer = (
        "\n<sub>Generated by "
        "[AI Code Review Assistant](https://github.com/SharmaSheetal/AI_CODE_REVIEW) · "
        "Powered by LLaMA-3 via Groq · Tree-sitter parsing</sub>"
    )

    return header + "\n".join(sections) + footer


async def main():
    pr_url = os.environ.get("PR_URL")
    if not pr_url:
        print("ERROR: PR_URL environment variable is not set.")
        sys.exit(1)

    print(f"Running AI review for: {pr_url}")

    # Import here so GITHUB_TOKEN and GROQ_API_KEY are already in the environment
    from backend.core.reviewer import run_review
    import time

    start = time.time()
    result = await run_review(pr_url=pr_url, include_tests=True, include_bug_detection=True)
    result.processing_time_seconds = round(time.time() - start, 2)

    print(f"Found {result.total_suggestions} suggestions in {result.processing_time_seconds}s")

    # Post the comment on the PR
    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        print("WARNING: GITHUB_TOKEN not set — printing results to stdout instead.")
        print(format_comment(pr_url, result))
        return

    comment_body = format_comment(pr_url, result)

    client = Github(github_token)
    repo = client.get_repo(result.repo)
    pr = repo.get_pull(result.pr_number)

    # Remove any previous AI review comment to avoid stacking duplicates on re-runs
    for comment in pr.get_issue_comments():
        if "🤖 AI Code Review" in comment.body:
            comment.delete()

    pr.create_issue_comment(comment_body)
    print(f"Comment posted to PR #{result.pr_number}")


if __name__ == "__main__":
    asyncio.run(main())
